### ISSUE TITLE
Compiling error in develop branch

### ISSUE THREAD

**Issue by ohenrich** [ludwig-cf/ludwig#166]
Hi Kevin,

The `develop` branch of Ludwig does not compile using `openmpi/gcc-8.5.0/4.1.1` as `inttypes.h` are missing. I can only find inclusion of this header in /src/until.c, strangely in the middle of the code in line 1198. 

The version up to 27th Jan 2022 compiles, so I believe it must be because of commits on 28th Jan 2022: 

```
...
mpicc -fopenmp -D_D3Q19_  -O3 -g -DNDEBUG -DNSIMDVL=4 -fopenmp  -I.././target -c blue_phase_beris_edwards.c
In file included from field_psi_init_rt.h:20,
                 from field_psi_init_rt.c:21:
field.h:40:3: error: unknown type name ‘int8_t’
   int8_t cv[27][3];             /* Send/recv directions */
   ^~~~~~
make[3]: *** [Makefile:85: field_psi_init_rt.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from symmetric.h:20,
                 from fe_electro_symmetric.h:22,
                 from psi_force.c:27:
field.h:40:3: error: unknown type name ‘int8_t’
   int8_t cv[27][3];             /* Send/recv directions */
   ^~~~~~
In file included from psi_force.h:22,
                 from psi_force.c:28:
hydro.h:39:3: error: unknown type name ‘int8_t’
   int8_t cv[27][3];             /* Send/recv directions */
   ^~~~~~
make[3]: *** [Makefile:85: psi_force.o] Error 1
make[3]: Leaving directory '/users/xwb17127/code/ludwig/src'
make[2]: *** [Makefile:60: default] Error 2
make[2]: Leaving directory '/users/xwb17127/code/ludwig/src'
make[1]: *** [Makefile:25: build] Error 2
make[1]: Leaving directory '/users/xwb17127/code/ludwig'
make: *** [Makefile:15: default] Error 2
...
```

**Comment by kevinstratford** [comment]
Oops. Sorry. That's an oversight not picked up by any compiler I've got.
I was using actually `stdint.h` for `int8_t`, but that was missing...

**Comment by ohenrich** [comment]
No prob. This works and it compiles now without errors.
